### ISSUE TITLE
Add ability to use wildcards

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-cli-js#2]
Currently, the command line errors out when trying to using wildcards in filenames as the input for a pipe:

`flexio pipes run flexio-docs-assets-upload *.png`

Results in the following:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\dwilliams\Downloads\fx-docs-images\app*.png'
    at Error (native)
```

**Comment by biwillia** [comment]
Fixed
