### ISSUE TITLE
CLI Installation for NPM Not Working

### ISSUE THREAD

**Issue by natetrek** [flexiodata/flexio-cli-js#4]
The NPM installation command for the CLI not working:  npm install -g flexio

When you run this command, you get the following error messages:

> npm ERR! path C:\Users\nwilliams\AppData\Roaming\npm\node_modules\flexio\src\main
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall chmod
> npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\nwilliams\AppData\Roaming\npm\node_modules\flexio\src\main'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\nwilliams\AppData\Roaming\npm-cache\_logs\2017-11-28T21_09_01_350Z-debug.log

**Comment by biwillia** [comment]
Fixed.
